packages:
  - "apps/*"
  - chrome-extension
  - pages/*
  - packages/*
  - tests/*

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver